/** Traduzione dei tipi Google Maps (inglese, da Outscraper) in italiano. */
const TIPI: Record<string, string> = {
  Restaurant: "Ristorante",
  "Italian restaurant": "Ristorante",
  "Sardinian restaurant": "Ristorante",
  "Seafood restaurant": "Ristorante di pesce",
  "Pizza restaurant": "Pizzeria",
  "Pizza delivery": "Pizzeria",
  "Pizza Takeout": "Pizzeria",
  "Fast food restaurant": "Fast food",
  "Hamburger restaurant": "Hamburgeria",
  "Sushi restaurant": "Ristorante sushi",
  "Japanese restaurant": "Ristorante giapponese",
  "Small plates restaurant": "Ristorante",
  "Steak house": "Steakhouse",
  Bistro: "Bistrot",
  Gastropub: "Pub",
  Pub: "Pub",
  Brewpub: "Birreria",
  Bar: "Bar",
  "Espresso bar": "Bar",
  "Coffee shop": "Bar",
  "Cocktail bar": "Cocktail bar",
  "Wine bar": "Enoteca",
  Bakery: "Panificio",
  "Pastry shop": "Pasticceria",
  "Cake shop": "Pasticceria",
  "Sandwich shop": "Paninoteca",
  Deli: "Gastronomia",
  Hotel: "Hotel",
  "Extended stay hotel": "Hotel",
  "Bed & breakfast": "B&B",
  Farmstay: "Agriturismo",
  Lodging: "Struttura ricettiva",
  Campground: "Campeggio",
  Dentist: "Studio dentistico",
  "Dental clinic": "Studio dentistico",
  Orthodontist: "Ortodontista",
  Doctor: "Studio medico",
  "Family practice physician": "Medico",
  "General practitioner": "Medico",
  Dermatologist: "Dermatologo",
  "Medical Center": "Centro medico",
  "Local medical services": "Centro medico",
  Veterinarian: "Veterinario",
  "Animal hospital": "Clinica veterinaria",
  "Veterinary pharmacy": "Farmacia veterinaria",
  "Hair salon": "Parrucchiere",
  Hairdresser: "Parrucchiere",
  "Beauty salon": "Centro estetico",
  "Esthetics service": "Centro estetico",
  Pharmacy: "Farmacia",
  "Pet supply store": "Negozio per animali",
};

/** Categorie da non contattare: enti pubblici e simili. */
export const TIPI_ESCLUSI = new Set([
  "City or town hall",
  "Labor union",
  "Hospital",
  "General hospital",
  "Public medical center",
  "Beach",
  "Wildlife rescue service",
  "Government office",
  "School",
  "Church",
  "Police",
]);

export function tipoItaliano(tipo: string): string {
  return TIPI[tipo] || tipo;
}
